export const ADS_GET_REQUEST = "ADS_GET_REQUEST"
export const ADS_GET_SUCCESS = "ADS_GET_SUCCESS"
export const ADS_GET_FAIL = "ADS_GET_FAIL"

export const ADS_DELETE_REQUEST = "ADS_DELETE_REQUEST"
export const ADS_DELETE_SUCCESS = "ADS_DELETE_SUCCESS"
export const ADS_DELETE_FAIL = "ADS_DELETE_FAIL"


