export const BANNER_GET_REQUEST = "BANNER_GET_REQUEST"
export const BANNER_GET_SUCCESS = "BANNER_GET_SUCCESS"
export const BANNER_GET_FAIL = "BANNER_GET_FAIL"

export const BANNER_DELETE_GET_REQUEST = "BANNER_DELETE_GET_REQUEST"
export const BANNER_DELETE_GET_SUCCESS = "BANNER_DELETE_GET_SUCCESS"
export const BANNER_DELETE_GET_FAIL = "BANNER_DELETE_GET_FAIL"
