export const BLOGS_GET_REQUEST = "BLOGS_GET_REQUEST"
export const BLOGS_GET_SUCCESS = "BLOGS_GET_SUCCESS"
export const BLOGS_GET_FAIL = "BLOGS_GET_FAIL"

export const BLOGS_DELETE_REQUEST = "BLOGS_DELETE_REQUEST"
export const BLOGS_DELETE_SUCCESS = "BLOGS_DELETE_SUCCESS"
export const BLOGS_DELETE_FAIL = "BLOGS_DELETE_FAIL"



