export const NEWS_GET_REQUEST = "NEWS_GET_REQUEST"
export const NEWS_GET_SUCCESS = "NEWS_GET_SUCCESS"
export const NEWS_GET_FAIL = "NEWS_GET_FAIL"

export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST"
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS"
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL"

