export const PARTNER_GET_REQUEST = "PARTNER_GET_REQUEST"
export const PARTNER_GET_SUCCESS = "PARTNER_GET_SUCCESS"
export const PARTNER_GET_FAIL = "PARTNER_GET_FAIL"

export const PARTNER_DELETE_REQUEST = "PARTNER_DELETE_REQUEST"
export const PARTNER_DELETE_SUCCESS = "PARTNER_DELETE_SUCCESS"
export const PARTNER_DELETE_FAIL = "PARTNER_DELETE_FAIL"

