export const SHOWCASE_GET_REQUEST = "SHOWCASE_GET_REQUEST"
export const SHOWCASE_GET_SUCCESS = "SHOWCASE_GET_SUCCESS"
export const SHOWCASE_GET_FAIL = "SHOWCASE_GET_FAIL"

export const SHOWCASE_DELETE_REQUEST = "SHOWCASE_DELETE_REQUEST"
export const SHOWCASE_DELETE_SUCCESS = "SHOWCASE_DELETE_SUCCESS"
export const SHOWCASE_DELETE_FAIL = "SHOWCASE_DELETE_FAIL"
