export const TESTIMONIAL_GET_REQUEST = "TESTIMONIAL_GET_REQUEST"
export const TESTIMONIAL_GET_SUCCESS = "TESTIMONIAL_GET_SUCCESS"
export const TESTIMONIAL_GET_FAIL = "TESTIMONIAL_GET_FAIL"

export const TESTIMONIAL_DELETE_REQUEST = "TESTIMONIAL_DELETE_REQUEST"
export const TESTIMONIAL_DELETE_SUCCESS = "TESTIMONIAL_DELETE_SUCCESS"
export const TESTIMONIAL_DELETE_FAIL = "TESTIMONIAL_DELETE_FAIL"